import {
  Inject,
  Injectable,
  Logger,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';
import Database from 'better-sqlite3';
import * as fs from 'fs';
import * as path from 'path';
import { SERVICE_CONFIG } from '../config/config';
import type { ServiceConfig } from '../config/config';

export type Db = Database.Database;

@Injectable()
export class DatabaseService implements OnModuleInit, OnModuleDestroy {
  private readonly log = new Logger(DatabaseService.name);
  private db?: Db;

  constructor(@Inject(SERVICE_CONFIG) private readonly cfg: ServiceConfig) {}

  onModuleInit(): void {
    const file = this.cfg.database.file;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    this.db = new Database(file);
    this.db.pragma('journal_mode = WAL');
    this.db.pragma('foreign_keys = ON');
    this.migrate();
    this.log.log(`SQLite ready at ${file}`);
  }

  onModuleDestroy(): void {
    this.db?.close();
  }

  get connection(): Db {
    if (!this.db) throw new Error('Database not initialized');
    return this.db;
  }

  private migrate(): void {
    this.renameLegacyAgentEvents();
    this.dropLegacyPersonaTables();
    this.connection.exec(`
      CREATE TABLE IF NOT EXISTS sessions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        app_id TEXT NOT NULL,
        persona_name TEXT,
        persona_system_prompt TEXT,
        channel TEXT,
        client_version TEXT,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE INDEX IF NOT EXISTS idx_sessions_user
        ON sessions(user_id);
    `);
    this.alterSessionsForPersonaVariable();
    this.ensureSessionsTokenCounter();
    this.connection.exec(`
      CREATE TABLE IF NOT EXISTS messages (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        parts_json TEXT,
        created_at TEXT NOT NULL,
        seq INTEGER NOT NULL
      );

      CREATE INDEX IF NOT EXISTS idx_messages_session_seq
        ON messages(session_id, seq);

      CREATE TABLE IF NOT EXISTS decision_events (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        correlation_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        command TEXT,
        summary TEXT NOT NULL,
        payload_json TEXT,
        created_at TEXT NOT NULL,
        seq INTEGER NOT NULL
      );

      CREATE INDEX IF NOT EXISTS idx_decision_events_session_seq
        ON decision_events(session_id, seq);

      CREATE INDEX IF NOT EXISTS idx_decision_events_turn_seq
        ON decision_events(turn_id, seq);

      CREATE TABLE IF NOT EXISTS agent_plans (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
        turn_id TEXT NOT NULL,
        correlation_id TEXT NOT NULL,
        title TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE INDEX IF NOT EXISTS idx_agent_plans_session_status
        ON agent_plans(session_id, status, updated_at);

      CREATE TABLE IF NOT EXISTS agent_plan_steps (
        id TEXT PRIMARY KEY,
        plan_id TEXT NOT NULL REFERENCES agent_plans(id) ON DELETE CASCADE,
        step_index INTEGER NOT NULL,
        title TEXT NOT NULL,
        details TEXT,
        status TEXT NOT NULL DEFAULT 'pending',
        note TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(plan_id, step_index)
      );

      CREATE INDEX IF NOT EXISTS idx_agent_plan_steps_plan
        ON agent_plan_steps(plan_id, step_index);
    `);
  }

  /**
   * Phase F1 of the v5 refactor renames `agent_events` to
   * `decision_events`. The semantic became "decisions taken by the
   * orchestrator flow"; the `agent_*` prefix is reserved for the
   * future agent surface (`agent_plans`, `agent_plan_steps` stay).
   *
   * If the legacy table exists, rename it in place and recreate the
   * indexes. Idempotent: if the rename has already happened, this is
   * a no-op.
   */
  /**
   * Per the v5 ownership update, persona is a UI-owned concept. The
   * orchestrator no longer stores any persona definition; it only holds
   * the variable (name + systemPrompt) sent by the client on session
   * create. Drop the old persona tables if they exist; the data was
   * always derived from a hardcoded seed and can be regenerated by the
   * UI on the next session.
   */
  private dropLegacyPersonaTables(): void {
    const personaTables = [
      'persona_identity_facts',
      'persona_identity_versions',
      'persona_identity_snapshots',
      'persona_life_events',
      'persona_reflections',
      'persona_user_relationships',
      'identity_mutation_candidates',
      'personas',
    ];
    const present = personaTables.filter((name) =>
      this.connection
        .prepare(
          `SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`,
        )
        .get(name),
    );
    if (present.length === 0) return;
    this.log.log(
      `Dropping ${present.length} legacy persona table(s): ${present.join(', ')}`,
    );
    // FKs between persona_* tables are CASCADE on personas, so order
    // matters. Disable FK enforcement during the drop to be safe.
    this.connection.pragma('foreign_keys = OFF');
    try {
      const tx = this.connection.transaction((tables: string[]) => {
        for (const t of tables) {
          this.connection.exec(`DROP TABLE IF EXISTS ${t};`);
        }
      });
      tx(present);
    } finally {
      this.connection.pragma('foreign_keys = ON');
    }
  }

  /**
   * Migrates the `sessions` table from the v4-era schema
   * (`persona_id TEXT`) to the v5 schema
   * (`persona_name TEXT`, `persona_system_prompt TEXT`).
   * The persona definition now flows from the UI on session.create.
   */
  private alterSessionsForPersonaVariable(): void {
    const cols = this.connection
      .prepare(`PRAGMA table_info('sessions')`)
      .all() as Array<{ name: string }>;
    const names = new Set(cols.map((c) => c.name));
    if (names.has('persona_id')) {
      this.log.log('Migrating sessions.persona_id → persona_name + persona_system_prompt');
      this.connection.exec(`ALTER TABLE sessions DROP COLUMN persona_id;`);
    }
    if (!names.has('persona_name')) {
      this.connection.exec(`ALTER TABLE sessions ADD COLUMN persona_name TEXT;`);
    }
    if (!names.has('persona_system_prompt')) {
      this.connection.exec(
        `ALTER TABLE sessions ADD COLUMN persona_system_prompt TEXT;`,
      );
    }
  }

  /**
   * Adds `sessions.total_token_count` (INTEGER NOT NULL DEFAULT 0).
   * Bumped on every persisted turn by ChatSessionService.appendTurn,
   * so the orchestrator can quickly know "how big has this session
   * grown" without iterating every message. Used by the prompt
   * budget logic (Unit J): when the running total approaches the
   * model's promptBudgetTokens, the assembly switches from "all raw"
   * to "summary + as much raw as fits".
   */
  private ensureSessionsTokenCounter(): void {
    const cols = this.connection
      .prepare(`PRAGMA table_info('sessions')`)
      .all() as Array<{ name: string }>;
    if (cols.some((c) => c.name === 'total_token_count')) return;
    this.connection.exec(
      `ALTER TABLE sessions ADD COLUMN total_token_count INTEGER NOT NULL DEFAULT 0;`,
    );
    this.log.log('Added column sessions.total_token_count');
  }

  private renameLegacyAgentEvents(): void {
    const legacy = this.connection
      .prepare(
        `SELECT name FROM sqlite_master WHERE type='table' AND name='agent_events'`,
      )
      .get() as { name: string } | undefined;
    if (!legacy) return;

    this.log.log(
      'Migrating legacy agent_events table to decision_events (Phase F1).',
    );

    this.connection.exec(`
      DROP INDEX IF EXISTS idx_agent_events_session_seq;
      DROP INDEX IF EXISTS idx_agent_events_turn_seq;
      ALTER TABLE agent_events RENAME TO decision_events;
    `);
  }
}
